### ISSUE TITLE
Repository names

### ISSUE THREAD

**Issue by tischi** [mobie-org/platybrowser-datasets#52]
@constantinpape 
some things here may be to platynereis-centric.
- the organisation name could rather be `mmb`
- the repo `platybrowser` could be named `platynereis` (since it does not actually contain the browser, just the data....)

**Comment by constantinpape** [comment]
Yes, good points.
I will have a look how much effort it would be to rename an organization.
Renaming the repo is easy.

**Comment by tischi** [comment]
Before we do it: I am still unhappy with the MultiModalBrowser. It just does not flow....
Since we are using it now a lot I think we should consider one more time to give it a beautiful name....

**Comment by constantinpape** [comment]
> Before we do it: I am still unhappy with the MultiModalBrowser. It just does not flow....
> Since we are using it now a lot I think we should consider one more time to give it a beautiful name....

Yeah, good point. We can also ask the others again when we talk next week.

**Comment by constantinpape** [comment]
To recap some points @tischi and me discussed earlier:
- we will rename the org and the mmb to MOBiE (for the org, we will probably just do everything lowercase, so that urls are less complicated).

We also plan on pulling a few more repositories in here, that contain the source data for the fiji plugin (and maybe other tools that can read it in the future).
We should have a naming scheme for these, for example appending `source`, so we would have:
- platynereis-source
- covid-em-source
- autophagosomes-clem-source

etc.

**Comment by tischi** [comment]
1. MoBIE (not MOBiE) 
2. What about `-datasets` instead of `-source`? Would fit the datasets.json

**Comment by constantinpape** [comment]
> * MoBIE (not MOBiE)
> 

Yes, but I think we should have the org just lower case.
Otherwise URLs get a bit complicated.

> * What about `-datasets` instead of `-source`? Would fit the datasets.json

I like `-datasets` better than `-source` too.

**Comment by tischi** [comment]
yes, URLs lower case!

**Comment by constantinpape** [comment]
all done
